[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "cache_forge"
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
# Adding remappings for OpenZeppelin contracts
remappings = [
    "@chainlink/=lib/chainlink/",
    "@chainlink/contracts/=lib/chainlink/contracts/",
    "@chainlink/contracts-ccip/=lib/chainlink/contracts-ccip/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

[profile.ci]
fuzz = { runs = 1_000 }
verbosity = 4

# For invariant testing configuration
[invariant]
runs = 1000
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "https://ethereum-sepolia.publicnode.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Dependencies
[profile.deps]
solc = "0.8.20"
