name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
          npm install --save-dev @babel/plugin-transform-react-jsx
          npm install --save-dev tailwindcss postcss autoprefixer
      
      - name: Build Static Page
        env:
          VITE_SKIP_TS_CHECK: true
          TSC_COMPILE_ON_ERROR: true
          NODE_ENV: production
        run: |
          cd frontend
          # Create .env file
          echo "VITE_SKIP_TS_CHECK=true" > .env
          echo "TSC_COMPILE_ON_ERROR=true" >> .env
          
          # Create dist directory and index.html
          mkdir -p dist
          cat > dist/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>LendFlow - DeFi Lending Platform</title>
            <style>
              body {
                font-family: 'Inter', system-ui, sans-serif;
                margin: 0;
                padding: 0;
                background: linear-gradient(to right, #3b82f6, #8b5cf6);
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
                color: #333;
              }
              .container {
                background-color: white;
                border-radius: 0.75rem;
                box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);
                width: 90%;
                max-width: 32rem;
                padding: 2rem;
              }
              h1 {
                color: #3b82f6;
                font-size: 1.875rem;
                text-align: center;
                margin-bottom: 1.5rem;
                font-weight: 700;
              }
              h2 {
                color: #4b5563;
                font-size: 1.25rem;
                text-align: center;
                margin-bottom: 1rem;
                font-weight: 600;
              }
              p {
                color: #4b5563;
                margin-bottom: 1rem;
              }
              ul {
                list-style-type: disc;
                padding-left: 1.5rem;
                margin-bottom: 1.5rem;
                color: #4b5563;
              }
              li {
                margin-bottom: 0.5rem;
              }
              .info-box {
                background-color: #eff6ff;
                border-radius: 0.5rem;
                padding: 1rem;
                margin-bottom: 1.5rem;
              }
              .info-box h3 {
                color: #2563eb;
                font-weight: 600;
                margin-top: 0;
                margin-bottom: 0.5rem;
                font-size: 1rem;
              }
              .info-box p {
                font-size: 0.875rem;
                margin-bottom: 0;
              }
              .button-container {
                display: flex;
                flex-direction: column;
                gap: 0.75rem;
              }
              .button {
                padding: 0.5rem 1rem;
                border-radius: 0.5rem;
                text-align: center;
                font-weight: 500;
                text-decoration: none;
                transition: background-color 0.2s;
              }
              .primary-button {
                background-color: #3b82f6;
                color: white;
              }
              .primary-button:hover {
                background-color: #2563eb;
              }
              .secondary-button {
                border: 1px solid #3b82f6;
                color: #3b82f6;
              }
              .secondary-button:hover {
                background-color: #eff6ff;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>LendFlow</h1>
              <h2>DeFi Lending Platform</h2>
              
              <div>
                <p>Welcome to LendFlow, a decentralized lending platform that allows users to:</p>
                <ul>
                  <li>Supply assets as collateral</li>
                  <li>Borrow assets against your collateral</li>
                  <li>Earn interest on supplied assets</li>
                  <li>Manage lending positions with real-time health monitoring</li>
                </ul>
              </div>
              
              <div class="info-box">
                <h3>About This Project</h3>
                <p>This DeFi platform was built using React, Hardhat, and Solidity smart contracts. The full functionality requires a local blockchain environment.</p>
              </div>
              
              <div class="button-container">
                <a href="https://github.com/wooyoungkang123/LendFlow" class="button primary-button" target="_blank" rel="noopener noreferrer">View on GitHub</a>
                <a href="https://github.com/wooyoungkang123/LendFlow#readme" class="button secondary-button" target="_blank" rel="noopener noreferrer">Read Documentation</a>
              </div>
            </div>
          </body>
          </html>
          EOL
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'frontend/dist'
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 